### ISSUE TITLE
Trojan detected in the latest release

### ISSUE THREAD

**Issue by akxer** [IBangedMyToaster/Rule34.us.Downloader#6]
Detected: Trojanscript/Wacatac.H!ml
Status: Active
Active threats have not been remediated and are running on your device.
Date: 29-12-2022 01:09
Details: This program is dangerous and executes commands from an attacker.
Affected items:
file: C:\Users\testuser\Downloads\rule34.us.Downloader-win-x64\rule34.us
Downloader.exe

**Comment by IBangedMyToaster** [comment]
Hey akxer, thanks for letting me know.
Ill look into this and keep you updated

**Comment by IBangedMyToaster** [comment]
I have tweaked the Project and can’t seem to reproduce the error anymore. In case the error persists, I would advise you to [manually allow the program](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26) to run in the security settings or [deactivate the real-time protection](https://support.microsoft.com/en-us/windows/turn-off-defender-antivirus-protection-in-windows-security-99e6004f-c54c-8509-773c-a4d776b77960) while downloading the release.

It is interesting to know that this detection is a result of the defender’s machine learning regarding the real-time protection and is in fact a **false positive**.
> Though this machine learning is really used throughout Defender's operation, it's most prevalent within certain specific detections which are designated by a suffix of "!ml" attached to the end of the detection name, which you should note is included in the one which detected your app.

> Since these detections are related specifically to machine learning, they are inherently also found via real-time protection, so manual or automated scans will not find them.

Let me know if this workaround did the trick for you.
